import { requireAdminPermission } from "../../../../src/lib/admin/authorization";
import { getAdminDb } from "../../../../src/lib/admin/db";
import { requireAdminUser } from "../../../../src/lib/admin/session";
import { createGeoAuditRepository } from "@seovista/worker";
import type { AdminLeadListRow } from "@seovista/worker";

export default async function AdminLeadsPage(): Promise<React.ReactElement> {
  const user = await requireAdminUser();
  await requireAdminPermission(user, "admin:overview:read");

  const db = getAdminDb();
  const geoRepo = createGeoAuditRepository(db);
  const leads = await geoRepo.getAllLeadsForAdmin();

  return (
    <main id="admin-main" className="mx-auto max-w-7xl" aria-labelledby="admin-leads-title">
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
        <div>
          <p className="text-sm font-semibold uppercase tracking-[0.18em] text-spectral">Client CRM</p>
          <h1 id="admin-leads-title" className="mt-2 text-3xl font-semibold tracking-tight text-ink">GEO Audit Leads</h1>
          <p className="mt-2 text-sm text-muted-ink">Client domains and lead capture emails generated by the GEO Readiness Checker.</p>
        </div>
      </div>

      <section className="admin-card mt-8 p-6" aria-labelledby="lead-activity-title">
        <div className="flex items-center justify-between border-b border-hairline pb-4">
          <h2 id="lead-activity-title" className="text-lg font-semibold text-ink">Captured Leads ({leads.length})</h2>
        </div>
        
        <div className="mt-6 overflow-x-auto">
          {leads.length === 0 ? (
            <p className="py-8 text-center text-sm text-muted-ink">No leads captured yet.</p>
          ) : (
            <table className="min-w-full text-left text-sm">
              <thead className="bg-mineral text-xs font-semibold uppercase tracking-wider text-muted-ink">
                <tr>
                  <th className="px-4 py-3">Domain</th>
                  <th className="px-4 py-3">Brand & Market</th>
                  <th className="px-4 py-3">Email</th>
                  <th className="px-4 py-3">Consent</th>
                  <th className="px-4 py-3">Job Status</th>
                  <th className="px-4 py-3">Date</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-hairline bg-white">
                {leads.map((lead: AdminLeadListRow) => (
                  <tr key={lead.id} className="hover:bg-mineral/50">
                    <td className="px-4 py-3 font-medium text-ink">{lead.domain}</td>
                    <td className="px-4 py-3 text-muted-ink">
                      <div>{lead.brandName}</div>
                      <div className="text-xs text-muted-ink">{lead.primaryMarket}</div>
                    </td>
                    <td className="px-4 py-3 text-muted-ink">{lead.workEmail || <span className="text-muted-ink italic">Pre-email</span>}</td>
                    <td className="px-4 py-3">
                      {lead.marketingConsent ? (
                        <span className="inline-flex items-center rounded bg-signal px-2 py-0.5 text-[10px] font-medium text-signal-foreground">Yes</span>
                      ) : (
                        <span className="inline-flex items-center rounded bg-mineral px-2 py-0.5 text-[10px] font-medium text-muted-ink">No</span>
                      )}
                    </td>
                    <td className="px-4 py-3">{getJobStatusBadge(lead.jobStatus)}</td>
                    <td className="px-4 py-3 text-muted-ink">{new Date(lead.createdAt).toLocaleDateString("en-GB", { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute:'2-digit' })}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </section>
    </main>
  );
}

function getJobStatusBadge(status: string | null) {
  if (!status) return <span className="text-muted-ink italic">None</span>;
  const normalized = status.toLowerCase();
  
  if (normalized === 'completed') {
    return <span className="inline-flex items-center rounded-full bg-spectral/10 px-2 py-0.5 text-xs font-medium text-spectral">{status}</span>;
  }
  if (normalized === 'failed') {
    return <span className="inline-flex items-center rounded-full bg-destructive/10 px-2 py-0.5 text-xs font-medium text-destructive">{status}</span>;
  }
  if (normalized === 'running' || normalized === 'queued') {
    return <span className="inline-flex items-center rounded-full border border-ember/20 bg-ember/10 px-2 py-0.5 text-xs font-medium text-ember">{status}</span>;
  }
  return <span className="inline-flex items-center rounded-full bg-mineral px-2 py-0.5 text-xs font-medium text-muted-ink">{status}</span>;
}








