import { requireAdminPermission } from "../../../../src/lib/admin/authorization";
import { getAdminDb } from "../../../../src/lib/admin/db";
import { requireAdminUser } from "../../../../src/lib/admin/session";
import { createGeoAuditRepository } from "@seovista/worker";
import type { AdminLeadListRow } from "@seovista/worker";

export default async function AdminLeadsPage(): Promise<React.ReactElement> {
  const user = await requireAdminUser();
  await requireAdminPermission(user, "admin:overview:read");

  const db = getAdminDb();
  const geoRepo = createGeoAuditRepository(db);
  const leads = await geoRepo.getAllLeadsForAdmin();

  return (
    <main id="admin-main" className="mx-auto max-w-7xl" aria-labelledby="admin-leads-title">
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
        <div>
          <p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-700">Client CRM</p>
          <h1 id="admin-leads-title" className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">GEO Audit Leads</h1>
          <p className="mt-2 text-sm text-slate-600">Client domains and lead capture emails generated by the GEO Readiness Checker.</p>
        </div>
      </div>

      <section className="admin-card mt-8 p-6" aria-labelledby="lead-activity-title">
        <div className="flex items-center justify-between border-b border-slate-100 pb-4">
          <h2 id="lead-activity-title" className="text-lg font-semibold text-slate-950">Captured Leads ({leads.length})</h2>
        </div>
        
        <div className="mt-6 overflow-x-auto">
          {leads.length === 0 ? (
            <p className="py-8 text-center text-sm text-slate-500">No leads captured yet.</p>
          ) : (
            <table className="min-w-full text-left text-sm">
              <thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wider text-slate-500">
                <tr>
                  <th className="px-4 py-3">Domain</th>
                  <th className="px-4 py-3">Brand & Market</th>
                  <th className="px-4 py-3">Email</th>
                  <th className="px-4 py-3">Consent</th>
                  <th className="px-4 py-3">Job Status</th>
                  <th className="px-4 py-3">Date</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 bg-white">
                {leads.map((lead: AdminLeadListRow) => (
                  <tr key={lead.id} className="hover:bg-slate-50/50">
                    <td className="px-4 py-3 font-medium text-slate-900">{lead.domain}</td>
                    <td className="px-4 py-3 text-slate-600">
                      <div>{lead.brandName}</div>
                      <div className="text-xs text-slate-400">{lead.primaryMarket}</div>
                    </td>
                    <td className="px-4 py-3 text-slate-600">{lead.workEmail || <span className="text-slate-400 italic">Pre-email</span>}</td>
                    <td className="px-4 py-3">
                      {lead.marketingConsent ? (
                        <span className="inline-flex items-center rounded bg-emerald-100 px-2 py-0.5 text-[10px] font-medium text-emerald-800">Yes</span>
                      ) : (
                        <span className="inline-flex items-center rounded bg-slate-100 px-2 py-0.5 text-[10px] font-medium text-slate-500">No</span>
                      )}
                    </td>
                    <td className="px-4 py-3">{getJobStatusBadge(lead.jobStatus)}</td>
                    <td className="px-4 py-3 text-slate-500">{new Date(lead.createdAt).toLocaleDateString("en-GB", { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute:'2-digit' })}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </section>
    </main>
  );
}

function getJobStatusBadge(status: string | null) {
  if (!status) return <span className="text-slate-400 italic">None</span>;
  const normalized = status.toLowerCase();
  
  if (normalized === 'completed') {
    return <span className="inline-flex items-center rounded-full bg-blue-50 px-2 py-0.5 text-xs font-medium text-blue-700">{status}</span>;
  }
  if (normalized === 'failed') {
    return <span className="inline-flex items-center rounded-full bg-red-50 px-2 py-0.5 text-xs font-medium text-red-700">{status}</span>;
  }
  if (normalized === 'running' || normalized === 'queued') {
    return <span className="inline-flex items-center rounded-full border border-amber-200 bg-amber-50 px-2 py-0.5 text-xs font-medium text-amber-700">{status}</span>;
  }
  return <span className="inline-flex items-center rounded-full bg-slate-100 px-2 py-0.5 text-xs font-medium text-slate-600">{status}</span>;
}








