export type {
  PublicationStatus,
  LocaleCode,
  Provenance,
  CollectionName,
  DeferredCollectionName,
  PublicCollectionName,
  CanonicalInfo,
  IndexationInfo,
  BaseContent,
  Page,
  Service,
  Tool,
  Article,
  Author,
  Organization,
  ResearchReport,
  Definition,
  FAQ,
  Source,
  Redirect,
  Locale,
  AuditLead,
  ContentEntity,
  DomainEntity,
  ContentProjection,
  PublicMode,
  PreviewMode,
  PreviewAuthorization,
  ReadMode,
  MapOptions,
  MapResult,
  MapFailure,
  MapOutcome,
  EligibilityCheck,
  ResolvedPage,
  ResolvedService,
  ResolvedTool,
  ResolvedArticle,
  ResolvedResearchReport,
  ResolvedDefinition,
  ResolvedFAQ,
  ResolvedContentEntity,
  ResolvedEntity,
  RelationshipDiagnostic,
  RelationshipField,
  ResolveOptions,
  EntityIndex,
  Adapter,
} from "./types.js";

export {
  mapEntity,
  mapCollection,
  mapCollectionEnvelope,
  mapPage,
  mapService,
  mapTool,
  mapArticle,
  mapAuthor,
  mapOrganization,
  mapResearchReport,
  mapDefinition,
  mapFAQ,
  mapSource,
  mapRedirect,
  mapLocale,
  mapAuditLead,
  toMapFailure,
} from "./mapper.js";

export {
  createAdapter,
  buildEntityIndex,
  resolveSingle,
  resolveMany,
  resolvePage,
  resolveService,
  resolveTool,
  resolveArticle,
  resolveResearchReport,
  resolveDefinition,
  resolveFAQ,
  resolveContentEntity,
} from "./adapter.js";

export {
  normalizeIndexation,
  validateIndexationCombination,
  isPubliclyEligible,
  isPreviewAuthorized,
  isContentEntityPubliclyEligible,
  isSitemapEligible,
  isFeedEligible,
  isJsonLdEligible,
  isLocalePubliclyEligible,
  isRedirectPubliclyEligible,
  isAuditLeadPrivate,
} from "./publication.js";

export {
  SPRINT_ZERO_COLLECTION_MATRIX,
  SPRINT_ZERO_COLLECTIONS,
  isSprintZeroCollection,
  validateSprintZeroRegistration,
  relationshipContractFor,
  type CollectionVisibility,
  type RelationshipCardinality,
  type RelationshipContract,
  type CollectionContract,
} from "./collection-matrix.js";

export { validateLocale, defaultLocale, isEnglish, isHreflangEligible } from "./locale.js";

export {
  resolveCanonical,
  validateRedirect,
  validateRedirectSet,
  parseTrustedSiteUrl,
  isTrustedUrl,
  siteUrlSchema,
  type TrustedSiteUrl,
  type RedirectInput,
  type ValidatedRedirect,
} from "./canonical.js";

export const name: string = "@seovista/content-models";
