/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as GeoRouteImport } from './routes/geo'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as DigitalAuthorityRouteImport } from './routes/digital-authority'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsGeoReadinessCheckerRouteImport } from './routes/tools.geo-readiness-checker'
import { Route as DesignStatesRouteImport } from './routes/design.states'
import { Route as DesignContrastRouteImport } from './routes/design.contrast'
import { Route as ApiHealthRouteImport } from './routes/api/health'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoRoute = GeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalAuthorityRoute = DigitalAuthorityRouteImport.update({
  id: '/digital-authority',
  path: '/digital-authority',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsGeoReadinessCheckerRoute =
  ToolsGeoReadinessCheckerRouteImport.update({
    id: '/geo-readiness-checker',
    path: '/geo-readiness-checker',
    getParentRoute: () => ToolsRoute,
  } as any)
const DesignStatesRoute = DesignStatesRouteImport.update({
  id: '/design/states',
  path: '/design/states',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignContrastRoute = DesignContrastRouteImport.update({
  id: '/design/contrast',
  path: '/design/contrast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/digital-authority': typeof DigitalAuthorityRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/geo': typeof GeoRoute
  '/insights': typeof InsightsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seo': typeof SeoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/design/contrast': typeof DesignContrastRoute
  '/design/states': typeof DesignStatesRoute
  '/tools/geo-readiness-checker': typeof ToolsGeoReadinessCheckerRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/digital-authority': typeof DigitalAuthorityRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/geo': typeof GeoRoute
  '/insights': typeof InsightsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seo': typeof SeoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/health': typeof ApiHealthRoute
  '/design/contrast': typeof DesignContrastRoute
  '/design/states': typeof DesignStatesRoute
  '/tools/geo-readiness-checker': typeof ToolsGeoReadinessCheckerRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/digital-authority': typeof DigitalAuthorityRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/geo': typeof GeoRoute
  '/insights': typeof InsightsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seo': typeof SeoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/design/contrast': typeof DesignContrastRoute
  '/design/states': typeof DesignStatesRoute
  '/tools/geo-readiness-checker': typeof ToolsGeoReadinessCheckerRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/digital-authority'
    | '/feed.xml'
    | '/geo'
    | '/insights'
    | '/llms.txt'
    | '/privacy'
    | '/robots.txt'
    | '/seo'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/api/health'
    | '/design/contrast'
    | '/design/states'
    | '/tools/geo-readiness-checker'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/digital-authority'
    | '/feed.xml'
    | '/geo'
    | '/insights'
    | '/llms.txt'
    | '/privacy'
    | '/robots.txt'
    | '/seo'
    | '/sitemap.xml'
    | '/terms'
    | '/api/health'
    | '/design/contrast'
    | '/design/states'
    | '/tools/geo-readiness-checker'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/digital-authority'
    | '/feed.xml'
    | '/geo'
    | '/insights'
    | '/llms.txt'
    | '/privacy'
    | '/robots.txt'
    | '/seo'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/api/health'
    | '/design/contrast'
    | '/design/states'
    | '/tools/geo-readiness-checker'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DigitalAuthorityRoute: typeof DigitalAuthorityRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  GeoRoute: typeof GeoRoute
  InsightsRoute: typeof InsightsRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SeoRoute: typeof SeoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  DesignContrastRoute: typeof DesignContrastRoute
  DesignStatesRoute: typeof DesignStatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo': {
      id: '/geo'
      path: '/geo'
      fullPath: '/geo'
      preLoaderRoute: typeof GeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-authority': {
      id: '/digital-authority'
      path: '/digital-authority'
      fullPath: '/digital-authority'
      preLoaderRoute: typeof DigitalAuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/geo-readiness-checker': {
      id: '/tools/geo-readiness-checker'
      path: '/geo-readiness-checker'
      fullPath: '/tools/geo-readiness-checker'
      preLoaderRoute: typeof ToolsGeoReadinessCheckerRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/design/states': {
      id: '/design/states'
      path: '/design/states'
      fullPath: '/design/states'
      preLoaderRoute: typeof DesignStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/contrast': {
      id: '/design/contrast'
      path: '/design/contrast'
      fullPath: '/design/contrast'
      preLoaderRoute: typeof DesignContrastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ToolsRouteChildren {
  ToolsGeoReadinessCheckerRoute: typeof ToolsGeoReadinessCheckerRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsGeoReadinessCheckerRoute: ToolsGeoReadinessCheckerRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DigitalAuthorityRoute: DigitalAuthorityRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  GeoRoute: GeoRoute,
  InsightsRoute: InsightsRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SeoRoute: SeoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  DesignContrastRoute: DesignContrastRoute,
  DesignStatesRoute: DesignStatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
